create table if not exists public.market (
  id bigint primary key generated by default as identity
);

alter table public.market
  add column if not exists pink_pool numeric not null default 500,
  add column if not exists blue_pool numeric not null default 500,
  add column if not exists revealed boolean not null default false,
  add column if not exists winner text,
  add column if not exists announcement text,
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

alter table public.market
  drop constraint if exists market_winner_check;

alter table public.market
  add constraint market_winner_check
  check (winner in ('pink', 'blue') or winner is null);

insert into public.market (id, pink_pool, blue_pool, revealed, winner, announcement)
values (1, 500, 500, false, null, null)
on conflict (id) do update
set
  pink_pool = excluded.pink_pool,
  blue_pool = excluded.blue_pool,
  revealed = excluded.revealed,
  winner = excluded.winner,
  announcement = excluded.announcement,
  updated_at = timezone('utc', now());

create or replace function public.place_market_bet(
  p_market_id bigint,
  p_side text,
  p_amount numeric
)
returns table (
  id bigint,
  pink_pool numeric,
  blue_pool numeric,
  revealed boolean,
  winner text,
  announcement text,
  updated_at timestamptz,
  shares_out numeric
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_market public.market%rowtype;
  v_k numeric;
  v_new_pink numeric;
  v_new_blue numeric;
  v_shares_out numeric;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception 'Bet amount must be positive';
  end if;

  if p_side not in ('pink', 'blue') then
    raise exception 'Side must be pink or blue';
  end if;

  select *
  into v_market
  from public.market as m
  where m.id = p_market_id
  for update;

  if not found then
    raise exception 'Market not found';
  end if;

  if v_market.revealed then
    raise exception 'Market already revealed';
  end if;

  v_k := v_market.pink_pool * v_market.blue_pool;

  if p_side = 'pink' then
    v_new_blue := v_market.blue_pool + p_amount;
    v_new_pink := v_k / v_new_blue;
    v_shares_out := v_market.pink_pool - v_new_pink;
  else
    v_new_pink := v_market.pink_pool + p_amount;
    v_new_blue := v_k / v_new_pink;
    v_shares_out := v_market.blue_pool - v_new_blue;
  end if;

  update public.market as m
  set
    pink_pool = v_new_pink,
    blue_pool = v_new_blue,
    updated_at = timezone('utc', now())
  where m.id = p_market_id
  returning
    m.id,
    m.pink_pool,
    m.blue_pool,
    m.revealed,
    m.winner,
    m.announcement,
    m.updated_at,
    v_shares_out
  into id, pink_pool, blue_pool, revealed, winner, announcement, updated_at, shares_out;

  return next;
end;
$$;

alter table public.market replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'market'
  ) then
    alter publication supabase_realtime add table public.market;
  end if;
end;
$$;

alter table public.market enable row level security;

drop policy if exists "market readable by everyone" on public.market;
create policy "market readable by everyone"
on public.market
for select
to anon, authenticated
using (true);

drop policy if exists "market updateable by everyone" on public.market;
create policy "market updateable by everyone"
on public.market
for update
to anon, authenticated
using (true)
with check (true);

grant select, update on public.market to anon, authenticated;
grant execute on function public.place_market_bet(bigint, text, numeric) to anon, authenticated;
